### PR TITLE
Service Layer for Donation Requirements and UI

### PR DESCRIPTION
**Pull request by woodward4422**
What this PR is for:
1. Building out a service layer that communicates with the glitch server that houses the donation requirements that we will get from charities
2. Built out the view controller that will show the donation requirements(TEMP)
3. Added button that will  push the DonationRequirementsViewController()

### CODE REVIEW

**Comment by LinnierGames** [comment]
[Regulations of what to donate](https://trello.com/c/D7Qb8zmi/17-regulations-of-what-to-donate)

**Comment by pondorasti** [comment]
Use Marks and Update the donation requirements UI.

**Review by pondorasti — DISMISSED** [review]
Use Marks and Update the donation requirements UI.

**Comment by LinnierGames** [comment]
[Fetch Regulations JSON](https://trello.com/c/U4Gzg6Ip/146-fetch-regulations-json)

**Comment by LinnierGames** [comment]
@Pondorasti what do you mean by "Update the donation requirements UI." ? And, where do marks need to be added?

**Review by LinnierGames — APPROVED** [review]

**Pull request merged**
