### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by LinnierGames**
### What's New
- TextFields are now updated using `.autocorrection` and `.autocapitalization`
- Dates are now formatted to be human readable
- Leaderboard populates the current user's info
- Small edits such as comments and populating the user reputations

### CODE REVIEW

**Comment by LinnierGames** [comment]
[Create a Date Formatter extension](https://trello.com/c/A7B3xgn8/124-create-a-date-formatter-extension)

**Comment by LinnierGames** [comment]
[Normalize all TextFields and TextViews](https://trello.com/c/6iyhhwPm/92-normalize-all-textfields-and-textviews)

**Comment by Pondorasti** [comment]
Looks good, what do you think about taking a more functional approach for setting the .autocorrection` and `.autocapitalization` of a textField

**Review by pondorasti — APPROVED** [review]
Looks good, what do you think about taking a more functional approach for setting the `.autocorrection` and `.autocapitalization` of a textField

**Comment by LinnierGames** [comment]
@pondorasti could you write a suggested change to describe how would we write a functional approach?

**Pull request merged**
