### PR TITLE
Review screens ui v2

### PR DESCRIPTION
**Pull request by pondorasti**
### VerifyDropoffViewController

- Nothing too fancy, just label with a picture and the usual button style sticked at the bottom of the screen

### ReviewCollaboratorViewController

- Created ReviewCollaboratorDescriptorView by subclassing an older module that we use in the Status Tab, CollaboratorDescriptorView
- Added Cosmos dependency for star rating

### Minor Improvements

- Refactored some names
- Color kfWhite was never therefore kfSuperWhite was replaced with kfWhite and then removed

### Notes

- Ignore TutorialViewController & SlideView, they will be reviewed in my other PR: https://github.com/Kifuapp/KifuSF/pull/24

### Update 1 by Erick

- Added logic to handle the communication between the backend layer and the ui

### Update 2 by Alex

- Tested the flow of the app, and updated the close button of each viewcontroller that gets presented modally
- Updated the following icons sizes: CloseIcon, FlagIcon, DisclosureIcon, PlusIcon
- Fixed some alignment problems from the WidgetView

### CODE REVIEW

**Comment by Pondorasti** [comment]
[Tutorial UI](https://trello.com/c/eeaoZEry/133-tutorial-ui)

**Comment by pondorasti** [comment]
[Design/Implement Reviews Screen/Popup](https://trello.com/c/EU2k7vIq/75-design-implement-reviews-screen-popup)

**Comment by LinnierGames** [comment]
@Pondorasti what I have left is for the whole thing to be tested. I haven't been able to present the ReviewVc due to being frustrated d:

Please do a test run by creating a donation and completing the donation with another user. You'll have to clear the database since i've updated from `dev` and the user objects are invalid

**Review by LinnierGames — CHANGES_REQUESTED** [review]
Please test the committed code by performing a test run. Everything else looks great

**Comment by pondorasti** [comment]
I have been testing the app a quite a bit to see if everything works, from a frontend perspective it looks just fine to me. One thing regarding the UX that we are missing in ReviewCollaboratorViewController is the way we handle the error if the user hasn't selected a review, we just ignore the touch received by the button, this could be further improved by using the same error label alongside the animation that we use in RegisterFormViewController or simply show an alert controller, here's a card regarding that https://trello.com/c/VTclybCW

**Comment by LinnierGames** [comment]
Sound great! Does the button support a disabled state? Thus we only enable it when there's a valid railting

**Comment by pondorasti** [comment]
Yup, the custom button is subclassing UIButton and has support for disabling the animation when the user interaction is not enabled.

**Comment by LinnierGames** [comment]
Maybe do that instead of prompting a message

**Review by LinnierGames — APPROVED** [review]

**Pull request merged**
